import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import SideNav from "@/components/nav/side-nav"
import TopNav from "@/components/nav/top-nav"
import { ThemeProvider } from "@/components/theme-provider"
// _app.tsx or index.tsx
import { QueryClient, QueryClientProvider } from "@tanstack/react-query"
import { AppProps } from "next/app"
import ReactQueryProvider from "@/utils/Providers"
import { Toaster } from "@/components/ui/sonner"

// Create a client

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body>
        <ReactQueryProvider>
          <ThemeProvider
            attribute='class'
            defaultTheme='system'
            enableSystem
            disableTransitionOnChange>
            {children}
          </ThemeProvider>
        </ReactQueryProvider>
        <Toaster />
      </body>
    </html>
  )
}
